xmlto.in: use correctly exit code from xsltproc
git-svn-id: https://svn.fedorahosted.org/svn/xmlto@77 eb1b79c1-ba03-4820-82f3-b60cf523859b

diff --git a/xmlto.in b/xmlto.in
--- a/xmlto.in
+++ b/xmlto.in
@@ -584,10 +584,13 @@ else
   # eval is for SEARCHPATH_FORMATTED's proper expansion
   eval "\"${XSLTPROC_PATH}\" ${XSLTOPTS} ${SEARCHPATH_FORMATTED} -o \"${XSLT_PROCESSED}\" \"${STYLESHEET}\" \"${INPUT_FILE}\""
 
+  # remember the xsltproc exit code for later checks
+  xsltproc_status=$?
+
   #xsltproc may return no file on empty input, touch it to have it for sure
   touch "$XSLT_PROCESSED"
 
-  if [ $? == 4 ]
+  if [ $xsltproc_status == 4 ]
   then
     XSLTOPTS="${XSLTOPTS} --catalogs"
     if [ "$VERBOSE" -ge 1 ]; then
@@ -595,9 +598,10 @@ else
 	echo -e >&2 "${XSLTPROC_PATH} ${XSLTOPTS} ${SEARCHPATH_FORMATTED}\\\\\n -o \"${XSLT_PROCESSED}\" \\\\\n \"${STYLESHEET}\" \\\\\n \"${INPUT_FILE}\""
     fi
     eval "\"${XSLTPROC_PATH}\"" ${XSLTOPTS} ${SEARCHPATH_FORMATTED} -o "\"${XSLT_PROCESSED}\"" "\"${STYLESHEET}\"" "\"${INPUT_FILE}\""
+    xsltproc_status=$?
   fi
 
-  xsltproc_status=$?
+  # xsltproc returned an exit code - exit the script
   [ ${xsltproc_status} -gt 0 ] && exit ${xsltproc_status}
 fi
 
